# Generated by Django 5.2.15 on 2026-06-17 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('excerpt', models.CharField(blank=True, default='', max_length=300)),
                ('body', models.TextField(blank=True, default='')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('cover_emoji', models.CharField(default='📝', max_length=10)),
                ('cover_color', models.CharField(choices=[('blue', 'blue'), ('green', 'green'), ('amber', 'amber'), ('rose', 'rose'), ('teal', 'teal'), ('violet', 'violet'), ('slate', 'slate')], default='green', max_length=10)),
                ('category', models.CharField(blank=True, default='Umumiy', max_length=60)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('is_featured', models.BooleanField(default=False)),
                ('read_minutes', models.PositiveSmallIntegerField(default=3)),
                ('views', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_featured', '-published_at', '-created_at'],
            },
        ),
    ]
