# Generated by Django 5.2.15 on 2026-06-12 06:00

from django.db import migrations, models


def blank_to_null(apps, schema_editor):
    """'' violates the new unique email constraint. The old column is still
    NOT NULL here, so give legacy rows a phone-derived placeholder email
    (same scheme as UserManager.create_user's phone fallback)."""
    User = apps.get_model('accounts', 'CustomUser')
    for u in User.objects.filter(email=''):
        base = (u.phone or f'user{u.pk}').lstrip('+')
        u.email = f'{base}@ionedu.uz'
        u.save(update_fields=['email'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_teammember'),
    ]

    operations = [
        migrations.RunPython(blank_to_null, migrations.RunPython.noop),
        migrations.AddField(
            model_name='passwordresetcode',
            name='email',
            field=models.EmailField(blank=True, db_index=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='phone',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
    ]
