# Generated by Django 5.2.15 on 2026-06-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_alter_test_options_test_category_test_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptanswer',
            name='selected_options',
            field=models.ManyToManyField(blank=True, related_name='+', to='tests.answeroption'),
        ),
        migrations.AddField(
            model_name='attemptanswer',
            name='text_answer',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single', "Bitta to'g'ri javob"), ('multiple', "Bir nechta to'g'ri javob"), ('true_false', "To'g'ri / Noto'g'ri"), ('text', 'Yozma javob')], default='single', max_length=12),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='finish_reason',
            field=models.CharField(blank=True, choices=[('manual', "O'zi yakunladi"), ('timeout', 'Vaqt tugadi'), ('focus_lost', 'Sahifadan chiqib ketdi'), ('left', 'Testni tark etdi')], default='', max_length=12),
        ),
    ]
